#!/bin/bash
cd $(dirname "${BASH_SOURCE[0]}")
source ./preflight-check
cd $DOCKER_PROJECT_FOLDER/scripts-generic

./build
./run $CONTAINER_NAME
./shell $CONTAINER_NAME
./stop $CONTAINER_NAME
./destroy $CONTAINER_NAME
