#!/bin/bash
cd $(dirname "${BASH_SOURCE[0]}")
source ./preflight-check
cd $DOCKER_PROJECT_FOLDER

# get name of container
if [ "$1" == "" ]
then
  echo "No container name specified."
  echo ""
  echo "To set a name for this container set the CONTAINER_NAME as an environment variable."
  echo "You can also run this command: '$(dirname "$0")/run [CONTAINER_NAME]'."
  echo ""
fi

echo "Using name '$CONTAINER_NAME' for this container..."
echo ""

# run the container and prevent it from stopping automatically with -td
#   * -t allocates a pseudo-TTY
#   * -d runs the container in the background
docker run --name $CONTAINER_NAME --hostname $CONTAINER_NAME -td $DOCKER_HUB_USERNAME$DOCKER_IMAGE_NAME$DOCKER_IMAGE_TAG
