#!/bin/bash
cd $(dirname "${BASH_SOURCE[0]}")
source ./preflight-check
cd $DOCKER_PROJECT_FOLDER/scripts-generic

# this will give the container root-level privileges
PRIVILEGED=1 ./run $CONTAINER_NAME
