#!/usr/bin/bash

# get name of container
if [ "$1" == "" ]
then
  CONTAINER_NAME=bullseye-slim-user-1
  echo "No container name specified."
  echo "To set a custom name for this container, run 'create [CONTAINER_NAME]'."
  echo ""
else
  CONTAINER_NAME="$1"
fi

echo "Using name '$CONTAINER_NAME' for this container..."
echo ""

# create the container and prevent it from stopping automatically with -td
#   - -t allocates a pseudo-TTY and -d runs the container in the background
docker run --name $CONTAINER_NAME --hostname bullseye-slim-user -td arcanemachine/bullseye-slim-user bash
