#!/bin/bash
cd $(dirname "${BASH_SOURCE[0]}")
source ./preflight-check
cd $DOCKER_PROJECT_FOLDER/scripts

./build
./push
./create $DOCKER_CONTAINER_NAME
./start $DOCKER_CONTAINER_NAME
./shell $DOCKER_CONTAINER_NAME
./stop $DOCKER_CONTAINER_NAME
./destroy $DOCKER_CONTAINER_NAME
