#!/bin/bash
cd $(dirname "${BASH_SOURCE[0]}")
source ./preflight-check
cd $DOCKER_PROJECT_FOLDER

SSH_HOST=$(./scripts/container-get-ip)

SSH_AUTH_SOCK='' ssh\
  -i ./id_rsa $DOCKER_CONTAINER_USER@$SSH_HOST\
  -o StrictHostKeyChecking=no
