#!/bin/bash
cd $(dirname "$0")

source .envrc

# require DOCKER_USERNAME to be set
if [ "$DOCKER_USERNAME" == "" ]
then
  echo "DOCKER_USERNAME not set"
  exit 1
fi

# require DOCKER_IMAGE_NAME to be set
if [ "$DOCKER_IMAGE_NAME" == "" ]
then
  echo "DOCKER_IMAGE_NAME not set"
  exit 1
fi

# require DOCKER_IMAGE_TAG to be set
if [ "$DOCKER_IMAGE_TAG" == "" ]
then
  echo "DOCKER_IMAGE_TAG not set. Using 'latest'..."
  export DOCKER_IMAGE_TAG=":latest"
else
  export DOCKER_IMAGE_TAG=":$DOCKER_IMAGE_TAG"
fi

# get name of container
if [ "$1" == "" ]
then
  export DOCKER_CONTAINER_NAME=$DOCKER_IMAGE_NAME-1
else
  export DOCKER_CONTAINER_NAME="$1"
fi
